services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    EzPlatformLogsUi\Bundle\EventListener\AdminMenuListener:
        tags:
            - { name: kernel.event_subscriber }
