services:
    EzPlatformLogsUi\Bundle\Controller\:
        resource: '../../Controller/*'
        autowire: true
        autoconfigure: true
        public: false
        exclude: '../../Controller/{Controller}'
